services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: veterinaria
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
