FROM node:20-alpine

WORKDIR /app

COPY front/package*.json ./
RUN npm install

COPY front/. .

ENV VITE_API_URL=http://localhost:3001/api

RUN npm run build

RUN npm install -g serve

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]